const films = [
  { id: 1, title: "Inception", director: "Christopher Nolan", year: 2010, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg" },
  { id: 2, title: "Le Parrain", director: "Francis Ford Coppola", year: 1972, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLegHnDmni2M.jpg" },
  { id: 3, title: "Interstellar", director: "Christopher Nolan", year: 2014, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg" },
  { id: 4, title: "Parasite", director: "Bong Joon-ho", year: 2019, genre: "Thriller", poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg" },
  { id: 5, title: "Titanic", director: "James Cameron", year: 1997, genre: "Romance", poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg" },
  { id: 6, title: "The Dark Knight", director: "Christopher Nolan", year: 2008, genre: "Action", poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg" },
  { id: 7, title: "Pulp Fiction", director: "Quentin Tarantino", year: 1994, genre: "Crime", poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg" },
  { id: 8, title: "Forrest Gump", director: "Robert Zemeckis", year: 1994, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg" },
  { id: 9, title: "Le Roi Lion", director: "Roger Allers", year: 1994, genre: "Animation", poster: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg" },
  { id: 10, title: "Avengers: Endgame", director: "Anthony et Joe Russo", year: 2019, genre: "Action", poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg" },
  { id: 11, title: "Spirited Away", director: "Hayao Miyazaki", year: 2001, genre: "Animation", poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg" },
  { id: 12, title: "Matrix", director: "Les Wachowski", year: 1999, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg" },
  { id: 13, title: "Le Silence des Agneaux", director: "Jonathan Demme", year: 1991, genre: "Thriller", poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg" },
  { id: 14, title: "Gladiator", director: "Ridley Scott", year: 2000, genre: "Action", poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg" },
  { id: 15, title: "Shrek", director: "Andrew Adamson", year: 2001, genre: "Animation", poster: "https://image.tmdb.org/t/p/w500/iB64vpL3dIObXicuOpB4CkC1gFj.jpg" },
  { id: 16, title: "Le Seigneur des Anneaux : La Communauté de l'Anneau", director: "Peter Jackson", year: 2001, genre: "Fantasy", poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg" },
  { id: 17, title: "Harry Potter à l'école des sorciers", director: "Chris Columbus", year: 2001, genre: "Fantasy", poster: "https://image.tmdb.org/t/p/w500/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg" },
  { id: 18, title: "Goodfellas", director: "Martin Scorsese", year: 1990, genre: "Crime", poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg" },
  { id: 19, title: "Fight Club", director: "David Fincher", year: 1999, genre: "Thriller", poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg" },
  { id: 20, title: "Schindler's List", director: "Steven Spielberg", year: 1993, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg" },
  { id: 21, title: "Jurassic Park", director: "Steven Spielberg", year: 1993, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg" },
  { id: 22, title: "Retour vers le Futur", director: "Robert Zemeckis", year: 1985, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg" },
  { id: 23, title: "Toy Story", director: "John Lasseter", year: 1995, genre: "Animation", poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg" },
  { id: 24, title: "Joker", director: "Todd Phillips", year: 2019, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg" },
  { id: 25, title: "Get Out", director: "Jordan Peele", year: 2017, genre: "Horreur", poster: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg" },
  { id: 26, title: "La La Land", director: "Damien Chazelle", year: 2016, genre: "Romance", poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg" },
  { id: 27, title: "1917", director: "Sam Mendes", year: 2019, genre: "Guerre", poster: "https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg" },
  { id: 28, title: "Whiplash", director: "Damien Chazelle", year: 2014, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg" },
  { id: 29, title: "Dune", director: "Denis Villeneuve", year: 2021, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/d5NXSklpcvkCgnEQ6GSPPJ2m3f5.jpg" },
  { id: 30, title: "Blade Runner 2049", director: "Denis Villeneuve", year: 2017, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg" },
  { id: 31, title: "Inglourious Basterds", director: "Quentin Tarantino", year: 2009, genre: "Guerre", poster: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg" },
  { id: 32, title: "Les Évadés", director: "Frank Darabont", year: 1994, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg" },
  { id: 33, title: "Coco", director: "Lee Unkrich", year: 2017, genre: "Animation", poster: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg" },
  { id: 34, title: "Knives Out", director: "Rian Johnson", year: 2019, genre: "Crime", poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2hmLinnoO2DRFnXL.jpg" },
  { id: 35, title: "Midsommar", director: "Ari Aster", year: 2019, genre: "Horreur", poster: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg" },
  { id: 36, title: "Everything Everywhere All at Once", director: "Daniel Kwan", year: 2022, genre: "Science-fiction", poster: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg" },
  { id: 37, title: "Top Gun: Maverick", director: "Joseph Kosinski", year: 2022, genre: "Action", poster: "https://image.tmdb.org/t/p/w500/62HCnUTHOWord73WL4XAgwIKGbK.jpg" },
  { id: 38, title: "Oppenheimer", director: "Christopher Nolan", year: 2023, genre: "Drame", poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg" },
];

module.exports = films;
